/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysgem;

import javax.swing.JOptionPane;

/**
 *
 * @author turin-turambar
 */
public class TelaAutenticar extends javax.swing.JFrame {

    /**
     * Creates new form TelaAutenticar
     */
    public TelaAutenticar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        System.out.println("Hello world");
        painelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        painelTitulo1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        painelTitulo2 = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        painelDados2 = new javax.swing.JPanel();
        lblEmail2 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        lblSenha2 = new javax.swing.JLabel();
        txtSenha2 = new javax.swing.JTextField();
        painelBotoes2 = new javax.swing.JPanel();
        btnConfirmar2 = new javax.swing.JButton();
        btnCancelar2 = new javax.swing.JButton();
        painelDados1 = new javax.swing.JPanel();
        lblEmail1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        lblSenha1 = new javax.swing.JLabel();
        txtSenha1 = new javax.swing.JTextField();
        painelBotoes1 = new javax.swing.JPanel();
        btnConfirmar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        painelDados = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        painelBotoes = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Autenticação");

        lblTitulo1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Autenticação");

        lblTitulo2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("Autenticação");

        javax.swing.GroupLayout painelTitulo2Layout = new javax.swing.GroupLayout(painelTitulo2);
        painelTitulo2.setLayout(painelTitulo2Layout);
        painelTitulo2Layout.setHorizontalGroup(
            painelTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTitulo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTitulo2Layout.setVerticalGroup(
            painelTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTitulo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDados2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEmail2.setText("E-mail:");

        txtEmail2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmail2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmail2FocusLost(evt);
            }
        });

        lblSenha2.setText("Senha:");

        txtSenha2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenha2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenha2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelDados2Layout = new javax.swing.GroupLayout(painelDados2);
        painelDados2.setLayout(painelDados2Layout);
        painelDados2Layout.setHorizontalGroup(
            painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDados2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail2)
                    .addComponent(lblSenha2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        painelDados2Layout.setVerticalGroup(
            painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDados2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEmail2)
                    .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSenha2)
                    .addComponent(txtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirmar2.setText("Confirmar");
        btnConfirmar2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnConfirmar2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnConfirmar2FocusLost(evt);
            }
        });
        btnConfirmar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmar2MouseExited(evt);
            }
        });
        btnConfirmar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmar2ActionPerformed(evt);
            }
        });

        btnCancelar2.setText("Cancelar");
        btnCancelar2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCancelar2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCancelar2FocusLost(evt);
            }
        });
        btnCancelar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelar2MouseExited(evt);
            }
        });
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoes2Layout = new javax.swing.GroupLayout(painelBotoes2);
        painelBotoes2.setLayout(painelBotoes2Layout);
        painelBotoes2Layout.setHorizontalGroup(
            painelBotoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoes2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmar2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBotoes2Layout.setVerticalGroup(
            painelBotoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoes2Layout.createSequentialGroup()
                .addGroup(painelBotoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelTitulo1Layout = new javax.swing.GroupLayout(painelTitulo1);
        painelTitulo1.setLayout(painelTitulo1Layout);
        painelTitulo1Layout.setHorizontalGroup(
            painelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelTitulo1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(painelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(painelTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelDados2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelBotoes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        painelTitulo1Layout.setVerticalGroup(
            painelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelTitulo1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(painelDados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(painelBotoes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        painelDados1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEmail1.setText("E-mail:");

        txtEmail1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmail1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmail1FocusLost(evt);
            }
        });

        lblSenha1.setText("Senha:");

        txtSenha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenha1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenha1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelDados1Layout = new javax.swing.GroupLayout(painelDados1);
        painelDados1.setLayout(painelDados1Layout);
        painelDados1Layout.setHorizontalGroup(
            painelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail1)
                    .addComponent(lblSenha1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        painelDados1Layout.setVerticalGroup(
            painelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEmail1)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSenha1)
                    .addComponent(txtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirmar1.setText("Confirmar");
        btnConfirmar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnConfirmar1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnConfirmar1FocusLost(evt);
            }
        });
        btnConfirmar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmar1MouseExited(evt);
            }
        });
        btnConfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmar1ActionPerformed(evt);
            }
        });

        btnCancelar1.setText("Cancelar");
        btnCancelar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCancelar1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCancelar1FocusLost(evt);
            }
        });
        btnCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelar1MouseExited(evt);
            }
        });
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoes1Layout = new javax.swing.GroupLayout(painelBotoes1);
        painelBotoes1.setLayout(painelBotoes1Layout);
        painelBotoes1Layout.setHorizontalGroup(
            painelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoes1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBotoes1Layout.setVerticalGroup(
            painelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoes1Layout.createSequentialGroup()
                .addGroup(painelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelTituloLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(painelTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addComponent(painelDados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelBotoes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelTituloLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(painelDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(painelBotoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        painelDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEmail.setText("E-mail:");

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        lblSenha.setText("Senha:");

        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(lblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEmail, txtSenha});

        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmail, txtSenha});

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnConfirmarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnConfirmarFocusLost(evt);
            }
        });
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseExited(evt);
            }
        });
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCancelarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCancelarFocusLost(evt);
            }
        });
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnConfirmar});

        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        painelBotoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnConfirmar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // chama a função campos vázios, ela retorna false se todos estiverem preenchidos.
        if (camposVazios() == false) {
            // cria uma caixa de diálogo, com a mensagem "Login Correto".
            JOptionPane.showMessageDialog(null, "Login correto");
            // Cria um objeto da Classe Tela Principal
            TelaPrincipal tela = new TelaPrincipal();
            // torna a tela Principal visível
            // o método setVisible torna uma tela visivel(true) ou invisivel(false)
            tela.setVisible(true);
            // torna essa tela(telaAutentica) invisível.
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // finaliza o programa.
        // A função exit da classe System finaliza a aplicação, o valor 0 indica que não há erros.
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseEntered
        // primeiro atributo é a font: "Ubuntu" pega a fonte do S.O
        // segundo atributo define a caracteristica: 0 simples, 1 negrito, 2 italico, 3 negrito e italico
        // terceiro atributo define a o tamanho da fonte
        btnConfirmar.setFont(new java.awt.Font("Ubuntu", 1, 15));
        btnConfirmar.setBackground(new java.awt.Color(234, 234, 35));
        // método setFont modifica a fonte do botão
        // método setBackground modifica a cor do botão ou de qualquer componente, a maioria tem esse método.
    }//GEN-LAST:event_btnConfirmarMouseEntered

    private void btnConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseExited
        btnConfirmar.setFont(new java.awt.Font("Ubuntu", 0, 15));
        btnConfirmar.setBackground(new java.awt.Color(249, 249, 248));
    }//GEN-LAST:event_btnConfirmarMouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setFont(new java.awt.Font("Ubuntu", 1, 15));
        btnCancelar.setBackground(new java.awt.Color(234, 234, 35));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setFont(new java.awt.Font("Ubuntu", 0, 15));
        btnCancelar.setBackground(new java.awt.Color(249, 249, 248));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        txtEmail.setBackground(new java.awt.Color(234, 234, 35));
        txtEmail.setFont(new java.awt.Font("Ubuntu", 1, 15));
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        txtEmail.setBackground(new java.awt.Color(249, 249, 248));
        txtEmail.setFont(new java.awt.Font("Ubuntu", 0, 15));
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        txtSenha.setBackground(new java.awt.Color(234, 234, 35));
        txtSenha.setFont(new java.awt.Font("Ubuntu", 1, 15));
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        txtSenha.setBackground(new java.awt.Color(249, 249, 248));
        txtSenha.setFont(new java.awt.Font("Ubuntu", 0, 15));
    }//GEN-LAST:event_txtSenhaFocusLost

    private void btnConfirmarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConfirmarFocusGained
        btnConfirmar.setFont(new java.awt.Font("Ubuntu", 1, 15));
        btnConfirmar.setBackground(new java.awt.Color(234, 234, 35));
    }//GEN-LAST:event_btnConfirmarFocusGained

    private void btnConfirmarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConfirmarFocusLost
        btnConfirmar.setFont(new java.awt.Font("Ubuntu", 0, 15));
        btnConfirmar.setBackground(new java.awt.Color(249, 249, 248));
    }//GEN-LAST:event_btnConfirmarFocusLost

    private void btnCancelarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelarFocusGained
        btnCancelar.setFont(new java.awt.Font("Ubuntu", 1, 15));
        btnCancelar.setBackground(new java.awt.Color(234, 234, 35));
    }//GEN-LAST:event_btnCancelarFocusGained

    private void btnCancelarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelarFocusLost
        btnCancelar.setFont(new java.awt.Font("Ubuntu", 0, 15));
        btnCancelar.setBackground(new java.awt.Color(249, 249, 248));
    }//GEN-LAST:event_btnCancelarFocusLost

    private void txtEmail1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmail1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1FocusGained

    private void txtEmail1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmail1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail1FocusLost

    private void txtSenha1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenha1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha1FocusGained

    private void txtSenha1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenha1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha1FocusLost

    private void btnConfirmar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConfirmar1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar1FocusGained

    private void btnConfirmar1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConfirmar1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar1FocusLost

    private void btnConfirmar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar1MouseEntered

    private void btnConfirmar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar1MouseExited

    private void btnConfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar1ActionPerformed

    private void btnCancelar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelar1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1FocusGained

    private void btnCancelar1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelar1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1FocusLost

    private void btnCancelar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1MouseEntered

    private void btnCancelar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1MouseExited

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void txtEmail2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmail2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail2FocusGained

    private void txtEmail2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmail2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail2FocusLost

    private void txtSenha2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenha2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha2FocusGained

    private void txtSenha2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenha2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenha2FocusLost

    private void btnConfirmar2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConfirmar2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar2FocusGained

    private void btnConfirmar2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConfirmar2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar2FocusLost

    private void btnConfirmar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar2MouseEntered

    private void btnConfirmar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar2MouseExited

    private void btnConfirmar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar2ActionPerformed

    private void btnCancelar2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelar2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar2FocusGained

    private void btnCancelar2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelar2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar2FocusLost

    private void btnCancelar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar2MouseEntered

    private void btnCancelar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar2MouseExited

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    /**
     * Função que verifica se os campos txtEmail e txtSenha estão vazios
     * @return (false) se os campos estiverem preenchidos e (true) se algum estiver vazio.
     */
    private boolean camposVazios() {        
        // pega o texto (getText()) do campo de texto txtEmail e compara(equals("") para verificar se o campo esta vazio.
        // o método equals retorna true se as duas Strings são iguais
        if (txtEmail.getText().equals("")) {            
            JOptionPane.showMessageDialog(null, "O Email é obrigatório", "Autenticação", JOptionPane.ERROR_MESSAGE);
            // o campo txtEmail recebe o foco (cursor)
            txtEmail.requestFocus();            
            return true;
        } else if (txtSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A senha é obrigatória", "Autenticação", JOptionPane.ERROR_MESSAGE);
            txtSenha.requestFocus();
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAutenticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAutenticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAutenticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAutenticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAutenticar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnConfirmar1;
    private javax.swing.JButton btnConfirmar2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenha1;
    private javax.swing.JLabel lblSenha2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelBotoes1;
    private javax.swing.JPanel painelBotoes2;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelDados1;
    private javax.swing.JPanel painelDados2;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JPanel painelTitulo1;
    private javax.swing.JPanel painelTitulo2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSenha1;
    private javax.swing.JTextField txtSenha2;
    // End of variables declaration//GEN-END:variables
}
